services:
  warehouseapi:
    image: ${DOCKER_REGISTRY-}warehouseapi
    build:
      context: .
      dockerfile: WarehouseAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - Jwt__Key=${JWT_KEY}